name: listtofile
description: Register list of paths into a file
keywords:
  - list
  - gawk
tools:
  - annotate:
      description: |
        Extract the file names from a list of path and register them into a file.
        The corresponding identifier can be added to the file in a second column
        or in a separate file.
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: List of paths to process
    - id:
        type: val
        description: List of identifiers to associate with the paths
output:
  - txt:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.id.txt":
          type: file
          description: File containing the file names and identifiers
          pattern: "*.id.txt"
      - "*.noid.txt":
          type: file
          description: File containing only the file names
          pattern: "*.noid.txt"
      - "*.idonly.txt":
          type: file
          description: File containing only the identifiers
          pattern: "*.idonly.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
