# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VCF_CHR_RENAME_BCFTOOLS"
description: Subworkflow to rename chromosomes in VCF files using bcftools
keywords:
  - VCF
  - chromosome
  - renaming
  - bcftools
components:
  - bcftools/annotate
input:
  - ch_vcf:
      description: Channel with input data
      structure:
        - meta:
          type: map
          description: Metadata map
        - vcf:
          type: file
          description: Input VCF file
          pattern: "*.{vcf,bcf,vcf.gz}"
        - index:
          type: file
          description: Input VCF index file
          pattern: "*.{tbi,csi}"
        - diff:
          type: string
          description: List of chromosomes to rename
        - prefix:
          type: string
          description: Should the 'chr' prefix be added or removed?
          enum: ["nochr", "chr"]
output:
  - vcf_renamed:
      description: Channel with renamed VCF files
      structure:
        - meta:
          type: map
          description: Metadata map
        - bam:
          type: file
          description: VCF file
          pattern: "*.{vcf,bcf,vcf.gz}"
        - index:
          type: file
          description: VCF index file
          pattern: "*.{tbi,csi}"
  - versions:
      description: Channel containing software versions file
      structure:
        - versions.yml:
            type: file
            description: File containing versions of the software used
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
