# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "BAM_IMPUTE_STITCH"
description: |
  Subworkflow to impute BAM files using STITCH software.
  Variants location to impute are obtain through the legend file given
keywords:
  - BAM
  - imputation
  - stitch
components:
  - gawk
  - stitch
  - bcftools/index
input:
  - ch_input:
      description: Channel with input data
      structure:
        - meta:
          type: map
          description: Metadata map
        - file:
          type: file
          description: List of input BAM files
          pattern: "*.[bam]"
        - index:
          type: file
          description: List of input index file
          pattern: "*.[bai|csi]"
        - bampaths:
          type: file
          description: |
            File containing the list of BAM/CRAM files to be phased.
            One file per line.
          pattern: "*.{txt,tsv}"
        - bamnames:
          type: file
          description: |
            File containing the sample names of each BAM files listed in bampaths.
            One file per line.
          pattern: "*.{txt,tsv}"
  - ch_posfile:
      description: Channel with position to call variants by chromosomes
      structure:
        - meta:
          type: map
          description: |
            Metadata map that will be combined with the input data map
            Need to have the "chr" as chromosome name and "id" as panel name
        - legend:
          type: file
          description: Region to extract from the BAM file
          pattern: "*.legend[.gz]+"
  - ch_region:
      description: Channel with region data
      structure:
        - meta:
          type: map
          description: Metadata map
        - region:
          type: string
          description: Region to extract from the BAM file
          pattern: "[chr]+[0-9]+:[0-9]+-[0-9]+"
  - ch_fasta:
      description: Channel with reference genome data
      structure:
        - meta:
          type: map
          description: Metadata map
        - fasta:
          type: file
          description: FASTA file of the reference genome
          pattern: "*.fa[sta]+"
        - fai:
          type: file
          description: FASTA index file of the reference genome
          pattern: "*.fai"
output:
  - vcf_tbi:
      description: Channel with imputed VCF files
      structure:
        - meta:
          type: map
          description: |
            Metadata map combined with the ch_panel data map.
            It contains the "chr" name of the ch_posfile map.
            {"tools" : "stitch"} is added.
        - vcf:
          type: file
          description: VCF imputed file
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: file
          description: VCF index file
          pattern: "*.[tbi|csi]"
  - versions:
      description: Channel containing software versions file
      structure:
        - versions.yml:
            type: file
            description: File containing versions of the software used
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
