# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VCF_PHASE_SHAPEIT5"
description: |
  Subworkflow to phase a reference panel VCF file using SHAPEIT5.
  The panel is first chunked by chromosome by glimpse2/chunk,
  then genotypes are phased with shapeit5/phasecommon and
  finally the chunks are merged back together by shapeit5/ligate by chromosomes.
keywords:
  - VCF
  - phase
  - shapeit5
  - haplotype
components:
  - glimpse2/chunk
  - shapeit5/phasecommon
  - shapeit5/ligate
  - bcftools/index
input:
  - ch_vcf:
      description: Channel with target VCF files
      structure:
        - meta:
          type: map
          description: Metadata map
        - vcf:
          type: File
          description: VCF file
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: File
          description: VCF index file
          pattern: "*.[tbi|csi]"
        - pedigree:
          type: file
          description: |
            Pedigree information in the following format: offspring father mother.
          pattern: "*.{txt, tsv}"
  - ch_region:
      description: Channel with region data
      structure:
        - meta:
          type: map
          description: Metadata map that will be combined with the input data map
        - region:
          type: string
          description: Region to extract from the BAM file
          pattern: "[chr]+[0-9]+:[0-9]+-[0-9]+"
  - ch_ref:
      description: Channel with reference phased VCF files
      structure:
        - meta:
          type: map
          description: Metadata map
        - vcf:
          type: File
          description: VCF file
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: File
          description: VCF index file
          pattern: "*.[tbi|csi]"
  - ch_scaffold:
      description: Channel with reference scaffold VCF files
      structure:
        - meta:
          type: map
          description: Metadata map
        - vcf:
          type: File
          description: VCF file
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: File
          description: VCF index file
          pattern: "*.[tbi|csi]"
  - ch_map:
      description: Channel with genetic map data (optional)
      structure:
        - meta:
          type: map
          description: Metadata map
        - map:
          type: File
          description: Map file
          pattern: "*.map"
  - chunk_model:
      description: Chunk model for Glimpse2
      type: string
      enum:
        - recursive
        - sequential
        - uniform-number-variants
output:
  - vcf_tbi:
      description: Channel with phased VCF files
      structure:
        - meta:
          type: map
          description: Metadata map
        - vcf:
          type: File
          description: VCF file
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: File
          description: VCF index file
          pattern: "*.[tbi|csi]"
  - versions:
      description: Channel containing software versions file
      structure:
        - versions.yml:
            type: file
            description: File containing versions of the software used
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
