# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VCF_IMPUTE_GLIMPSE1"
description: |
  Subworkflow to impute VCF files using GLIMPSE software by chunks of
  chromosomes. Chunks are then ligated to get the final VCF file by chromosomes.
keywords:
  - VCF
  - imputation
  - glimpse
components:
  - glimpse/phase
  - glimpse/ligate
  - bcftools/index
input:
  - ch_input:
      description: Channel with input data
      structure:
        - meta:
          type: map
          description: Metadata map
        - file:
          type: file
          description: Input VCF files
          pattern: "*.{vcf,bcf,vcf.gz}"
        - index:
          type: file
          description: Input index file
          pattern: "*.{tbi,csi}"
  - ch_panel:
      description: Channel with reference panel variants data
      structure:
        - meta:
          type: map
          description: |
            Metadata map that will be combined with the input data map
            Need to have the "chr" as chromosome name and "panel_id" as panel name
        - vcf:
          type: file
          description: Panel VCF files by chromosomes
          pattern: "*.{vcf,bcf,vcf.gz}"
        - index:
          type: file
          description: Panel VCF index files
          pattern: "*.{tbi,csi}"
  - ch_chunks:
      description: Channel with chunks region to impute by chromosomes
      structure:
        - meta:
          type: map
          description: |
            Metadata map that will be combined with the input data map
            Need to have the same map as ch_panel
        - region1:
          type: string
          description: Target region used for imputation, including left and right buffers
          pattern: "[chr][0-9]+:[0-9]+-[0-9]+"
        - region2:
          type: string
          description: Target imputed region, excluding left and right buffers
          pattern: "[chr][0-9]+:[0-9]+-[0-9]+"
output:
  - vcf_tbi:
      description: Channel with imputed VCF files
      structure:
        - meta:
          type: map
          description: |
            Metadata map combined with the ch_panel data map.
            {"tools" : "glimpse1"} is added.
        - vcf:
          type: file
          description: VCF imputed file merged by chromosomes
          pattern: "*.{vcf,bcf,vcf.gz}"
        - index:
          type: file
          description: VCF index file
          pattern: "*.{tbi,csi}"
  - versions:
      description: Channel containing software versions file
      structure:
        - versions.yml:
            type: file
            description: File containing versions of the software used
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
