# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "VCF_CONCATENATE_BCFTOOLS"
description: |
  Subworkflow to concatenate multiple VCF files using bcftools.
  VCF files will be grouped by meta map information: 'id', 'panel', 'tools', 'batch'.
  The aim is to concatenate all chromosomes.
  Concatenation is only performed if more than one VCF files is present for each group.
keywords:
  - VCF
  - chromosomes
  - concatenate
  - bcftools
components:
  - bcftools/concat
input:
  - ch_vcf_tbi:
      description: Channel with VCF files
      structure:
        - meta:
          type: map
          description: Metadata map
        - vcf:
          type: file
          description: VCF imputed file merged by chromosomes
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: file
          description: VCF index file
          pattern: "*.[tbi|csi]"
output:
  - vcf_tbi:
      description: Channel with VCF files concatenated
      structure:
        - meta:
          type: map
          description: |
            Metadata map with 'id', 'panel', 'tools', 'batch' and {'chr' : 'all'}
        - vcf:
          type: file
          description: VCF imputed file merged by chromosomes
          pattern: "*.[vcf|bcf|vcf.gz]"
        - index:
          type: file
          description: VCF index file
          pattern: "*.[tbi|csi]"
  - versions:
      description: Channel containing software versions file
      structure:
        - versions.yml:
            type: file
            description: File containing versions of the software used
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
